version: "3.8"

services:

  docker-jenkins:
    image: docker:dind
    privileged: true
    #env_file: .env
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    command: --storage-driver=overlay2

  jenkins-blueocean:
    build: ./jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_HOST=tcp://docker-jenkins:2376
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home

  jenkins-agent:
    image: jenkins/ssh-agent:jdk11
    env_file: .env
    ports:
      - "22:22"

volumes:
  jenkins-docker-certs:
  jenkins-data:
